config/routes.rb
Rails.application.routes.draw do
  resources :sites
  root 'sites#index'
  
  get 'sites/:id/show_json' => 'sites#show_json'

end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_reader :body, :robots_body
  
  validates :url, :format => URI::regexp(%w(http https))
  
  def include_word? word
    Processor.new(body, robots_body, uri).process_word?(word)
  end
  
  def can_fetch?
    Processor.new(body, robots_body, uri).can_fetch?
  end
  
  def emails
    Processor.new(body, robots_body, uri).process_emails
  end
  
  def body
    @body ||= Collector.new(self).collect_body
  end
  
  def robots_body
    @robots_body ||= Collector.new(self).collect_robots_body
  end
  
  private
  
  def uri
    URI(self.url)
  end
end

app/models/site/collector.rb
class Site
  class Collector
    attr_accessor :site, :uri, :body, :robots_body
    def initialize(site)
      @site = site
      @uri = URI(@site.url)
    end
    
    def collect_body
      response = Net::HTTP.get_response(@uri)
      case response
      when Net::HTTPSuccess
        encode_body(response.body)
      when Net::HTTPRedirection
        @site.update_attributes! url: response['location']
        self.uri = URI(@site.url)
        collect_body
      else
        nil
      end
    end
    
    def collect_robots_body
      robots_uri = URI("#{@uri.scheme}://#{@uri.host}/robots.txt")
      response = Net::HTTP.get_response(robots_uri)
      response.kind_of?(Net::HTTPSuccess) ? encode_body(response.body) : nil
    end
    
    private
    
    def encode_body(body)
      body.force_encoding('iso-8859-1').encode('utf-8')
    end
  end
end

app/models/site/processor.rb
class Site
  class Processor
    
    def initialize(body, robots_body, uri)
      @body = body
      @robots_body = robots_body
      @uri = uri
    end
    
    def process_emails
      addresses = []
      @body.scan(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i) do |email|
        addresses << email
      end
      addresses.uniq
    end
    
    def process_word? word
      !!(/#{word}/ =~ @body)
    end
    
    def can_fetch?
      has_robots? && robots_rule[@uri.path] != "Disallow"
    end
    
    
    private
    
    def has_robots?
      !!(@robots_body)
    end
    
    def robots_rule
      raw_rule = @robots_body
      return if @robots_body.nil?
      rules = {}
      raw_rule.split(/[\r\n]+/).each do |line|
        rule = line.split(": ")
        rules[rule[1]] = rule[0]
      end
      rules
    end
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy, :show_json]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end
  
  def show_json
    render :json => {
      url: @site.url,
      has_my_name: @site.include_word?('Chris'),
      using_boots_trap: @site.include_word?('bootstrap'),
      emails: @site.emails,
      body: @site.body
    }
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zugata</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sites</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.url %></td>
        <td><%= link_to 'Show as HTML', site %></td>
        <td><%= link_to 'Show as JSON', "sites/#{site.id}/show_json"%></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', sites_path %>
<p>
  <strong>Url:</strong>
  <%= @site.url %>
</p>
<p>
  <strong>Has my name? (Chris)</strong>
  <%= @site.include_word? 'chris' %>
</p>
<p>
  <strong>Using Bootstrap?</strong>
  <%= @site.include_word? 'bootstrap' %>
</p>
<p>
  <strong>Email Addresses</strong>
  <%= @site.emails %>
</p>
<p>
  <strong>Body</strong>
  <%= @site.body %>
</p>